BATTLE_SKILL_NARC_DIR := $(BUILD_NARC)/battle/skill
BATTLE_SKILL_TARGET := $(FILESYS)/battle/skill
BATTLE_SKILL_DEP_DIR := armips/asm/battle


BATTLE_EFFSCR_DIR := $(BUILD)/battle/scr/effscr
BATTLE_EFFSCR_NARC := $(BATTLE_SKILL_NARC_DIR)/be_seq.narc
BATTLE_EFFSCR_DEP_DIR := $(BATTLE_SKILL_DEP_DIR)/effscr

BATTLE_EFFSCR_SRCS := $(wildcard $(BATTLE_EFFSCR_DEP_DIR)/*.s)
BATTLE_EFFSCR_OBJS := $(patsubst $(BATTLE_EFFSCR_DEP_DIR)/effscr_%.s,$(BATTLE_EFFSCR_DIR)/be_seq_%.bin,$(BATTLE_EFFSCR_SRCS))

$(BATTLE_EFFSCR_DIR)/be_seq_%.bin: $(BATTLE_EFFSCR_DEP_DIR)/effscr_%.s
	$(ARMIPS) $<

$(BATTLE_EFFSCR_NARC): $(BATTLE_EFFSCR_OBJS)
	$(NARCHIVE) create $@ $(BATTLE_EFFSCR_DIR) -nf

NARC_FILES += $(BATTLE_EFFSCR_NARC)


BATTLE_MOVSCR_DIR := $(BUILD)/battle/scr/movscr
BATTLE_MOVSCR_NARC := $(BATTLE_SKILL_NARC_DIR)/waza_seq.narc
BATTLE_MOVSCR_DEP_DIR := $(BATTLE_SKILL_DEP_DIR)/movscr

BATTLE_MOVSCR_SRCS := $(wildcard $(BATTLE_MOVSCR_DEP_DIR)/*.s)
BATTLE_MOVSCR_OBJS := $(patsubst $(BATTLE_MOVSCR_DEP_DIR)/movscr_%.s,$(BATTLE_MOVSCR_DIR)/waza_seq_%.bin,$(BATTLE_MOVSCR_SRCS))

$(BATTLE_MOVSCR_DIR)/waza_seq_%.bin: $(BATTLE_MOVSCR_DEP_DIR)/movscr_%.s
	$(ARMIPS) $<

$(BATTLE_MOVSCR_NARC): $(BATTLE_MOVSCR_OBJS)
	$(NARCHIVE) create $@ $(BATTLE_MOVSCR_DIR) -nf

NARC_FILES += $(BATTLE_MOVSCR_NARC)

BATTLE_SUBSCR_DIR := $(BUILD)/battle/scr/subscr
BATTLE_SUBSCR_NARC := $(BATTLE_SKILL_NARC_DIR)/sub_seq.narc
BATTLE_SUBSCR_DEP_DIR := $(BATTLE_SKILL_DEP_DIR)/subscr

BATTLE_SUBSCR_SRCS := $(wildcard $(BATTLE_SUBSCR_DEP_DIR)/*.s)
BATTLE_SUBSCR_OBJS := $(patsubst $(BATTLE_SUBSCR_DEP_DIR)/subscr_%.s,$(BATTLE_SUBSCR_DIR)/sub_seq_%.bin,$(BATTLE_SUBSCR_SRCS))

$(BATTLE_SUBSCR_DIR)/sub_seq_%.bin: $(BATTLE_SUBSCR_DEP_DIR)/subscr_%.s
	$(ARMIPS) $<

$(BATTLE_SUBSCR_NARC): $(BATTLE_SUBSCR_OBJS)
	$(NARCHIVE) create $@ $(BATTLE_SUBSCR_DIR) -nf

NARC_FILES += $(BATTLE_SUBSCR_NARC)