#ifndef __CONSTANTS_MOVE_EFFECTS_H
#define __CONSTANTS_MOVE_EFFECTS_H

#define MOVE_EFFECT_NONE 0
#define MOVE_EFFECT_SLEEP_STATUS 1
#define MOVE_EFFECT_POISON_ON_HIT 2
#define MOVE_EFFECT_RECOVER_HALF_DAMAGE_DEALT 3
#define MOVE_EFFECT_BURN_ON_HIT 4
#define MOVE_EFFECT_FREEZE_ON_HIT 5
#define MOVE_EFFECT_PARALYZE_ON_HIT 6
#define MOVE_EFFECT_SELF_DESTRUCT 7
#define MOVE_EFFECT_DREAM_EATER 8
#define MOVE_EFFECT_MIRROR_MOVE 9
#define MOVE_EFFECT_RAISE_ATK_STATUS 10
#define MOVE_EFFECT_RAISE_DEF_STATUS 11
#define MOVE_EFFECT_RAISE_SPE_STATUS 12
#define MOVE_EFFECT_RAISE_SPA_STATUS 13
#define MOVE_EFFECT_RAISE_SPD_STATUS 14
#define MOVE_EFFECT_RAISE_ACC_STATUS 15
#define MOVE_EFFECT_RAISE_EVA_STATUS 16
#define MOVE_EFFECT_ALWAYS_HIT 17
#define MOVE_EFFECT_LOWER_ATK_STATUS 18
#define MOVE_EFFECT_LOWER_DEF_STATUS 19
#define MOVE_EFFECT_LOWER_SPE_STATUS 20
#define MOVE_EFFECT_LOWER_SPA_STATUS 21
#define MOVE_EFFECT_LOWER_SPD_STATUS 22
#define MOVE_EFFECT_LOWER_ACC_STATUS 23
#define MOVE_EFFECT_LOWER_EVA_STATUS 24
#define MOVE_EFFECT_RESET_STAT_CHANGES 25
#define MOVE_EFFECT_BIDE 26
#define MOVE_EFFECT_THRASH 27   // outrage, petal dance
#define MOVE_EFFECT_FORCE_SWITCH 28
#define MOVE_EFFECT_MULTI_HIT 29
#define MOVE_EFFECT_CONVERSION 30
#define MOVE_EFFECT_FLINCH_ON_HIT 31
#define MOVE_EFFECT_RESTORE_HALF_HP 32
#define MOVE_EFFECT_BADLY_POISONS 33
#define MOVE_EFFECT_PAY_DAY 34
#define MOVE_EFFECT_LIGHT_SCREEN 35
#define MOVE_EFFECT_RANDOM_BRN_PRZ_OR_PSN_ON_HIT 36 // tri attack
#define MOVE_EFFECT_REST 37
#define MOVE_EFFECT_ONE_HIT_KO 38
#define MOVE_EFFECT_CHARGE_TURN_HIGH_CRIT 39
#define MOVE_EFFECT_SUPER_FANG 40
#define MOVE_EFFECT_DRAGON_RAGE 41
#define MOVE_EFFECT_BINDING 42
#define MOVE_EFFECT_HIGH_CRITICAL 43
#define MOVE_EFFECT_HIT_TWICE 44
#define MOVE_EFFECT_CRASH_DAMAGE 45
#define MOVE_EFFECT_PREVENT_STAT_REDUCTION 46
#define MOVE_EFFECT_SHARPLY_RAISE_CRIT 47
#define MOVE_EFFECT_RECOIL_1_4 48
#define MOVE_EFFECT_CONFUSION_STATUS 49
#define MOVE_EFFECT_SHARPLY_RAISE_ATK_STATUS 50
#define MOVE_EFFECT_SHARPLY_RAISE_DEF_STATUS 51
#define MOVE_EFFECT_SHARPLY_RAISE_SPE_STATUS 52
#define MOVE_EFFECT_SHARPLY_RAISE_SPA_STATUS 53
#define MOVE_EFFECT_SHARPLY_RAISE_SPD_STATUS 54
#define MOVE_EFFECT_SHARPLY_RAISE_ACC_STATUS 55
#define MOVE_EFFECT_SHARPLY_RAISE_EVA_STATUS 56
#define MOVE_EFFECT_TRANSFORM 57
#define MOVE_EFFECT_SHARPLY_LOWER_ATK_STATUS 58
#define MOVE_EFFECT_SHARPLY_LOWER_DEF_STATUS 59
#define MOVE_EFFECT_SHARPLY_LOWER_SPE_STATUS 60
#define MOVE_EFFECT_SHARPLY_LOWER_SPA_STATUS 61
#define MOVE_EFFECT_SHARPLY_LOWER_ACC_STATUS 62
#define MOVE_EFFECT_SHARPLY_LOWER_EVA_STATUS 63
#define MOVE_EFFECT_SHARPLY_LOWER_SPD_STATUS 64 // 64 is inoperable in existing game code, use it for SpDef -2
#define MOVE_EFFECT_REFLECT 65
#define MOVE_EFFECT_POISON_STATUS 66
#define MOVE_EFFECT_PARALYZE_STATUS 67
#define MOVE_EFFECT_LOWER_ATK_ON_HIT 68
#define MOVE_EFFECT_LOWER_DEF_ON_HIT 69
#define MOVE_EFFECT_LOWER_SPE_ON_HIT 70
#define MOVE_EFFECT_LOWER_SPA_ON_HIT 71
#define MOVE_EFFECT_LOWER_SPD_ON_HIT 72
#define MOVE_EFFECT_LOWER_ACC_ON_HIT 73
#define MOVE_EFFECT_LOWER_EVA_ON_HIT 74
#define MOVE_EFFECT_CHARGE_TURN_HIGH_CRIT_AND_FLINCH 75
#define MOVE_EFFECT_CONFUSE_ON_HIT 76
#define MOVE_EFFECT_HIT_TWICE_POISON_ON_HIT 77
#define MOVE_EFFECT_VITAL_THROW 78
#define MOVE_EFFECT_SUBSTITUTE 79
#define MOVE_EFFECT_RECHARGE_TURN 80
#define MOVE_EFFECT_RAISE_ATK_WHEN_HIT 81 // Rage
#define MOVE_EFFECT_MIMIC 82
#define MOVE_EFFECT_METRONOME 83
#define MOVE_EFFECT_LEECH_SEED 84
#define MOVE_EFFECT_SPLASH 85
#define MOVE_EFFECT_DISABLE 86
#define MOVE_EFFECT_DEAL_DAMAGE_EQUAL_TO_LEVEL 87
#define MOVE_EFFECT_PSYWAVE 88
#define MOVE_EFFECT_COUNTER 89
#define MOVE_EFFECT_ENCORE 90
#define MOVE_EFFECT_PAIN_SPLIT 91
#define MOVE_EFFECT_SNORE 92
#define MOVE_EFFECT_CONVERSION2 93
#define MOVE_EFFECT_NEXT_ATTACK_ALWAYS_HITS 94
#define MOVE_EFFECT_SKETCH 95
// unused: 96
#define MOVE_EFFECT_SLEEP_TALK 97
#define MOVE_EFFECT_DESTINY_BOND 98
#define MOVE_EFFECT_HIGHER_POWER_WITH_LESS_HP 99 // Flail, Reversal
#define MOVE_EFFECT_SPITE 100
#define MOVE_EFFECT_LEAVE_WITH_1_HP 101
#define MOVE_EFFECT_HEAL_BELL 102
#define MOVE_EFFECT_PRIORITY_PLUS_1 103
#define MOVE_EFFECT_TRIPLE_KICK 104 // hits up to 3 times, power increases with each hit
#define MOVE_EFFECT_STEAL_HELD_ITEM 105
#define MOVE_EFFECT_PREVENT_ESCAPE 106
#define MOVE_EFFECT_NIGHTMARE 107 // if asleep, target takes damage equal to 1/4 max HP every turn
#define MOVE_EFFECT_MINIMIZE 108 // raise evasion, weak to Stomp, Rollout, Body Slam
#define MOVE_EFFECT_CURSE 109
// unused: 110
#define MOVE_EFFECT_PROTECT 111
#define MOVE_EFFECT_SPIKES 112
#define MOVE_EFFECT_FORESIGHT 113 // ignores evasion and normal/fighting can hit ghost
#define MOVE_EFFECT_FLAG_PERISH_SONG 114
#define MOVE_EFFECT_CAUSE_SANDSTORM 115
#define MOVE_EFFECT_ENDURE 116
#define MOVE_EFFECT_ROLLOUT 117
#define MOVE_EFFECT_SHARPLY_RAISE_TARGET_ATK_AND_CONFUSE 118 // Swagger
#define MOVE_EFFECT_DOUBLE_POWER_ON_CONSECUTIVE_HITS 119 // Fury Cutter
#define MOVE_EFFECT_INFATUATE 120
#define MOVE_EFFECT_RETURN 121
#define MOVE_EFFECT_PRESENT 122
#define MOVE_EFFECT_FRUSTRATION 123
#define MOVE_EFFECT_SAFEGUARD 124
#define MOVE_EFFECT_THAW_AND_BURN_ON_HIT 125
#define MOVE_EFFECT_MAGNITUDE 126
#define MOVE_EFFECT_BATON_PASS 127
#define MOVE_EFFECT_PURSUIT 128
#define MOVE_EFFECT_REMOVE_HAZARDS_AND_BINDING_EFFECTS 129 // Rapid Spin
#define MOVE_EFFECT_SONICBOOM 130
// unused: 131
#define MOVE_EFFECT_SYNTHESIS 132 // restores HP, amount depends on weather
// unused: 133
// unused: 134
#define MOVE_EFFECT_HIDDEN_POWER 135
#define MOVE_EFFECT_CAUSE_RAIN 136
#define MOVE_EFFECT_CAUSE_SUN 137
#define MOVE_EFFECT_RAISE_DEF_ON_HIT 138
#define MOVE_EFFECT_RAISE_ATK_ON_HIT 139
#define MOVE_EFFECT_RAISE_ALL_ON_HIT 140
// unused: 141
#define MOVE_EFFECT_BELLY_DRUM 142
#define MOVE_EFFECT_COPY_STAT_BOOSTS 143
#define MOVE_EFFECT_MIRROR_COAT 144
#define MOVE_EFFECT_CHARGE_TURN_RAISE_DEF 145
#define MOVE_EFFECT_FLINCH_DOUBLE_DAMAGE_FLY_OR_BOUNCE 146 // Twister
#define MOVE_EFFECT_DOUBLE_DAMAGE_ON_DIG 147 // Earthquake
#define MOVE_EFFECT_FUTURE_SIGHT 148
#define MOVE_EFFECT_DOUBLE_DAMAGE_FLY_OR_BOUNCE 149 // Gust
#define MOVE_EFFECT_DOUBLE_DAMAGE_MINIMIZE_FLINCH_ON_HIT 150
#define MOVE_EFFECT_CHARGE_TURN_UNLESS_SUN 151
#define MOVE_EFFECT_THUNDER 152
#define MOVE_EFFECT_FLEE_FROM_WILD_BATTLE 153 // Teleport
#define MOVE_EFFECT_BEAT_UP 154
#define MOVE_EFFECT_FLY 155
#define MOVE_EFFECT_RAISE_DEFENSE_DOUBLE_ROLLOUT_POWER 156
// unused: 157
#define MOVE_EFFECT_ALWAYS_FLINCH_ONLY_TURN_ONE 158
#define MOVE_EFFECT_UPROAR 159
#define MOVE_EFFECT_STOCKPILE 160
#define MOVE_EFFECT_SPIT_UP 161
#define MOVE_EFFECT_SWALLOW 162
// unused: 163
#define MOVE_EFFECT_CAUSE_HAIL 164
#define MOVE_EFFECT_TORMENT 165
#define MOVE_EFFECT_RAISE_TARGET_SPA_AND_CONFUSE 166 // Flatter
#define MOVE_EFFECT_BURN_STATUS 167 // Will-o-Wisp
#define MOVE_EFFECT_MEMENTO 168
#define MOVE_EFFECT_DOUBLE_POWER_IF_PSN_PRZ_BRN 169 // Facade
#define MOVE_EFFECT_FOCUS_PUNCH 170
#define MOVE_EFFECT_DOUBLE_POWER_AND_CURE_PRZ 171 // Smelling Salts
#define MOVE_EFFECT_FOLLOW_ME 172
#define MOVE_EFFECT_NATURE_POWER 173
#define MOVE_EFFECT_NEXT_MOVE_DOUBLE_DAMAGE_IF_ELECTRIC 174 // Charge
#define MOVE_EFFECT_TAUNT 175
#define MOVE_EFFECT_HELPING_HAND 176
#define MOVE_EFFECT_SWITCH_HELD_ITEMS 177 // Trick, Switcheroo
#define MOVE_EFFECT_COPY_ABILITY 178 // Role Play
#define MOVE_EFFECT_WISH 179
#define MOVE_EFFECT_ASSIST 180
#define MOVE_EFFECT_INGRAIN 181
#define MOVE_EFFECT_LOWER_USER_ATK_AND_DEF 182 // Superpower
#define MOVE_EFFECT_MAGIC_COAT 183
#define MOVE_EFFECT_RECYCLE 184
#define MOVE_EFFECT_DOUBLE_DAMAGE_IF_USER_HAS_BEEN_HIT 185 // Revenge, Avalanche
#define MOVE_EFFECT_REMOVE_SCREENS 186
#define MOVE_EFFECT_YAWN 187
#define MOVE_EFFECT_REMOVE_TARGET_HELD_ITEM 188 // Knock Off
#define MOVE_EFFECT_ENDEAVOR 189
#define MOVE_EFFECT_LOWER_POWER_WITH_LESS_HP 190 // Eruption, Water Spout
#define MOVE_EFFECT_SWITCH_ABILITIES 191 // Skill Swap
#define MOVE_EFFECT_FLAG_IMPRISON 192
#define MOVE_EFFECT_CURE_BRN_PSN_OR_PRZ 193 // Refresh
#define MOVE_EFFECT_FLAG_GRUDGE 194
#define MOVE_EFFECT_SNATCH 195
#define MOVE_EFFECT_HIGHER_POWER_ON_HEAVIER_TARGETS 196 // Low Kick, Grass Knot
#define MOVE_EFFECT_SECRET_POWER 197
#define MOVE_EFFECT_RECOIL_1_3 198
#define MOVE_EFFECT_CONFUSION_ON_HIT 199
#define MOVE_EFFECT_HIGH_CRIT_BURN_ON_HIT 200
#define MOVE_EFFECT_FLAG_MUD_SPORT 201
#define MOVE_EFFECT_BADLY_POISON_ON_HIT 202
#define MOVE_EFFECT_CHANGE_TYPE_WITH_WEATHER 203
#define MOVE_EFFECT_SHARPLY_LOWER_USER_SPA_ON_HIT 204
#define MOVE_EFFECT_LOWER_TARGET_ATK_AND_DEF_STATUS 205 // Tickle
#define MOVE_EFFECT_RAISE_DEF_AND_SPD_STATUS 206 // Cosmic Power
#define MOVE_EFFECT_SKY_UPPERCUT 207 // can hit during fly/bounce
#define MOVE_EFFECT_RAISE_ATK_AND_DEF_STATUS 208 // Bulk Up
#define MOVE_EFFECT_HIGH_CRIT_POISON_ON_HIT 209
#define MOVE_EFFECT_FLAG_WATER_SPORT 210
#define MOVE_EFFECT_RAISE_SPA_AND_SPD_STATUS 211 // Calm Mind
#define MOVE_EFFECT_RAISE_ATK_AND_SPE_STATUS 212 // Dragon Dance
#define MOVE_EFFECT_FLAG_CAMOUFLAGE 213
#define MOVE_EFFECT_ROOST 214
#define MOVE_EFFECT_GRAVITY 215
#define MOVE_EFFECT_DOUBLE_POWER_AND_CURE_SLP 216 // Wake-Up Slap (CHECK THAT THIS IS RIGHT)
#define MOVE_EFFECT_FLAG_MIRACLE_EYE 217 // ignores evasion and psychic can hit dark
#define MOVE_EFFECT_LOWER_SELF_SPE_ON_HIT 218 // Hammer Arm
#define MOVE_EFFECT_GYRO_BALL 219
#define MOVE_EFFECT_HEALING_WISH 220
#define MOVE_EFFECT_DOUBLE_POWER_IF_TARGET_BELOW_HALF 221 // Brine
#define MOVE_EFFECT_NATURAL_GIFT 222
#define MOVE_EFFECT_FEINT 223
#define MOVE_EFFECT_CONSUME_TARGET_BERY 224
#define MOVE_EFFECT_TAILWIND 225
#define MOVE_EFFECT_ACUPRESSURE 226 // sharply raise random stat of target
#define MOVE_EFFECT_METAL_BURST 227
#define MOVE_EFFECT_SWITCH_OUT_ON_HIT 228
#define MOVE_EFFECT_LOWER_DEF_AND_SPD_ON_HIT 229
#define MOVE_EFFECT_PAYBACK 230 // double power if user moves after target
#define MOVE_EFFECT_DOUBLE_DAMAGE_IF_TARGET_HAS_BEEN_HIT 231 // Assurance
#define MOVE_EFFECT_FLAG_EMBARGO 232
#define MOVE_EFFECT_FLING 233
#define MOVE_EFFECT_PSYCHO_SHIFT 234 // transfer status to target
#define MOVE_EFFECT_TRUMP_CARD 235 // higher power with less PP
#define MOVE_EFFECT_FLAG_HEAL_BLOCK 236
#define MOVE_EFFECT_WRING_OUT 237
#define MOVE_EFFECT_SWAP_ATK_AND_DEF_STATS 238 // Power Trick
#define MOVE_EFFECT_SUPPRESS_TARGET_ABILITY 239
#define MOVE_EFFECT_LUCKY_CHANT 240
#define MOVE_EFFECT_ME_FIRST 241
#define MOVE_EFFECT_USE_LAST_USED_MOVE 242 // Copycat
#define MOVE_EFFECT_POWER_SWAP 243 // Swap Atk and SpA stages
#define MOVE_EFFECT_GUARD_SWAP 244 // Swap Def and SpD stages
#define MOVE_EFFECT_PUNISHMENT 245 // power increases with each stat stage increase
#define MOVE_EFFECT_LAST_RESORT 246
#define MOVE_EFFECT_WORRY_SEED 247
#define MOVE_EFFECT_SUCKER_PUNCH 248
#define MOVE_EFFECT_TOXIC_SPIKES 249
#define MOVE_EFFECT_SWAP_STAT_CHANGES 250 // Heart Swap
#define MOVE_EFFECT_RESTORE_HP_AT_END_OF_TURN 251 // Aqua Ring
#define MOVE_EFFECT_FLAG_MAGNET_RISE 252
#define MOVE_EFFECT_RECOIL_1_3_BURN_ON_HIT 253
#define MOVE_EFFECT_STRUGGLE 254
#define MOVE_EFFECT_DIVE 255
#define MOVE_EFFECT_DIG 256
#define MOVE_EFFECT_DOUBLE_DAMAGE_ON_DIVE 257 // Surf
#define MOVE_EFFECT_DEFOG 258
#define MOVE_EFFECT_TRICK_ROOM 259
#define MOVE_EFFECT_BLIZZARD 260 // Always hit in hail, chance to freeze
#define MOVE_EFFECT_WHIRLPOOL 261
#define MOVE_EFFECT_RECOIL_1_3_PARALYZE_ON_HIT 262 // Volt Tackle
#define MOVE_EFFECT_BOUNCE 263
// unused: 264
#define MOVE_EFFECT_CAPTIVATE 265 // opposite gender target's SpA -2
#define MOVE_EFFECT_STEALTH_ROCK 266
#define MOVE_EFFECT_CHATTER 267
#define MOVE_EFFECT_JUDGMENT 268
#define MOVE_EFFECT_RECOIL_1_2 269
#define MOVE_EFFECT_LUNAR_DANCE 270
#define MOVE_EFFECT_SHARPLY_LOWER_SPD_ON_HIT 271
#define MOVE_EFFECT_FLAG_SHADOW_FORCE 272
#define MOVE_EFFECT_FLINCH_BURN_ON_HIT 273
#define MOVE_EFFECT_FLINCH_FREEZE_ON_HIT 274
#define MOVE_EFFECT_FLINCH_PARALYZE_ON_HIT 275
#define MOVE_EFFECT_RAISE_SPA_ON_HIT 276

#endif // __CONSTANTS_MOVE_EFFECTS_H