#include "global.h"
#include "battle/common.h"
#include "battle/moves.h"
#include "constants/moves.h"

/*
 * This is the master mapping of additional effects to subscripts, which is
 * used in battle orchestration. Individual move's effect scripts will set a
 * bitmask using the keys of this table into one of the VAR_EFFECT variables,
 * and the battle engine will use that key to determine which subscript to
 * invoke for follow-up logic.
 */
#if 0
static u32 sEffectToSubScript[] = {
    // Vanilla effects mapping
    [ADDL_EFFECT_NONE]              = 0,
    [ADDL_EFFECT_SLEEP]             = SUBSCR_APPLY_SLEEP,
    [ADDL_EFFECT_POISON]            = SUBSCR_APPLY_POISON,
    [ADDL_EFFECT_BURN]              = SUBSCR_APPLY_BURN,
    [ADDL_EFFECT_FREEZE]            = SUBSCR_APPLY_FREEZE,
    [ADDL_EFFECT_PARALYZE]          = SUBSCR_APPLY_PARALYSIS,
    [ADDL_EFFECT_BADLY_POISON]      = SUBSCR_BADLY_POISON,
    [ADDL_EFFECT_CONFUSE]           = SUBSCR_APPLY_CONFUSION,
    [ADDL_EFFECT_FLINCH]            = SUBSCR_TRY_FLINCH,
    [ADDL_EFFECT_REST]              = SUBSCR_REST,
    [ADDL_EFFECT_UPROAR]            = SUBSCR_UPROAR,
    [ADDL_EFFECT_PAYDAY]            = SUBSCR_PAY_DAY,
    [ADDL_EFFECT_CHARGE_TURN]       = SUBSCR_VANISH_ON_CHARGE_TURN,
    [ADDL_EFFECT_TRAP]              = SUBSCR_CLAMP_START,
    [ADDL_EFFECT_TAKE_RECOIL_1_4]   = SUBSCR_RECOIL_1_4,
    [ADDL_EFFECT_ATK_UP_1]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_DEF_UP_1]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPE_UP_1]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPA_UP_1]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPD_UP_1]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_ACC_UP_1]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_EVA_UP_1]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_ATK_DOWN_1]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_DEF_DOWN_1]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPE_DOWN_1]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPA_DOWN_1]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPD_DOWN_1]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_ACC_DOWN_1]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_EVA_DOWN_1]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_RECHARGE_TURN]     = SUBSCR_RECHARGE_MOVE,
    [ADDL_EFFECT_BUILD_RAGE]        = SUBSCR_RAGE_SET,
    [ADDL_EFFECT_STEAL_ITEM]        = SUBSCR_THIEF,
    [ADDL_EFFECT_MEAN_LOOK]         = SUBSCR_MEAN_LOOK,
    [ADDL_EFFECT_NIGHTMARE]         = SUBSCR_APPLY_NIGHTMARE,
    [ADDL_EFFECT_ALL_UP_1]          = SUBSCR_OMNIBOOST,
    [ADDL_EFFECT_RAPID_SPIN]        = SUBSCR_RAPID_SPIN,
    [ADDL_EFFECT_CURE_PARALYSIS]    = SUBSCR_HEAL_PARALYSIS,
    [ADDL_EFFECT_SUPERPOWER]        = SUBSCR_SUPERPOWER_DEBUFF,
    [ADDL_EFFECT_TAKE_RECOIL_1_3]   = SUBSCR_RECOIL_1_3,
    [ADDL_EFFECT_ATK_UP_2]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_DEF_UP_2]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPE_UP_2]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPA_UP_2]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPD_UP_2]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_ACC_UP_2]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_EVA_UP_2]          = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_ATK_DOWN_2]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_DEF_DOWN_2]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPE_DOWN_2]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPA_DOWN_2]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_SPD_DOWN_2]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_ACC_DOWN_2]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_EVA_DOWN_2]        = SUBSCR_BOOST_STATS,
    [ADDL_EFFECT_THRASH]            = SUBSCR_THRASHING,
    [ADDL_EFFECT_KNOCK_OFF]         = SUBSCR_KNOCK_OFF,
    [ADDL_EFFECT_COSMIC_POWER]      = SUBSCR_COSMIC_POWER,
    [ADDL_EFFECT_BULK_UP]           = SUBSCR_BULK_UP,
    [ADDL_EFFECT_TICKLE]            = SUBSCR_TICKLE,
    [ADDL_EFFECT_CALM_MIND]         = SUBSCR_CALM_MIND,
    [ADDL_EFFECT_DRAGON_DANCE]      = SUBSCR_DRAGON_DANCE,
    [ADDL_EFFECT_DRAIN_HALF_DAMAGE] = SUBSCR_DRAIN_HALF,
    [ADDL_EFFECT_DREAM_EATER]       = SUBSCR_DREAM_EATER,
    [ADDL_EFFECT_HAZE]              = SUBSCR_CLEAR_ALL_BOOSTS,
    [ADDL_EFFECT_BIDE]              = SUBSCR_START_BIDE,
    [ADDL_EFFECT_STRUGGLE]          = SUBSCR_STRUGGLE,
    [ADDL_EFFECT_CONVERSION]        = SUBSCR_CONVERSION,
    [ADDL_EFFECT_RECOVER_HALF_HP]   = SUBSCR_RECOVER_HALF_HP,
    [ADDL_EFFECT_LIGHT_SCREEN]      = SUBSCR_LIGHT_SCREEN,
    [ADDL_EFFECT_REFLECT]           = SUBSCR_REFLECT,
    [ADDL_EFFECT_MIST]              = SUBSCR_MIST,
    [ADDL_EFFECT_FOCUS_ENERGY]      = SUBSCR_FOCUS_ENERGY,
    [ADDL_EFFECT_MIMIC]             = SUBSCR_MIMIC,
    [ADDL_EFFECT_LEECH_SEED]        = SUBSCR_APPLY_LEECH_SEED,
    [ADDL_EFFECT_DISABLE]           = SUBSCR_APPLY_DISABLE,
    [ADDL_EFFECT_ENCORE]            = SUBSCR_APPLY_ENCORE,
    [ADDL_EFFECT_PAIN_SPLIT]        = SUBSCR_PAIN_SPLIT,
    [ADDL_EFFECT_CONVERSION_2]      = SUBSCR_CONVERSION_2,
    [ADDL_EFFECT_LOCK_ON]           = SUBSCR_LOCKON,
    [ADDL_EFFECT_SKETCH]            = SUBSCR_SKETCH,
    [ADDL_EFFECT_FEINT]             = SUBSCR_FEINT,
    [ADDL_EFFECT_DESTINY_BOND]      = SUBSCR_DESTINY_BOND,
    [ADDL_EFFECT_SPITE]             = SUBSCR_SPITE,
    [ADDL_EFFECT_PROTECT]           = SUBSCR_PROTECT,
    [ADDL_EFFECT_HEAL_BELL]         = SUBSCR_HEAL_BELL,
    [ADDL_EFFECT_SUBSTITUTE]        = SUBSCR_TRY_SUBSTITUTE,
    [ADDL_EFFECT_FORCE_SWITCH]      = SUBSCR_FORCE_OUT,
    [ADDL_EFFECT_TRANSFORM]         = SUBSCR_TRANSFORM,
    [ADDL_EFFECT_MINIMIZE]          = SUBSCR_MINIMIZE,
    [ADDL_EFFECT_CURSE]             = SUBSCR_CURSE_BOOST,
    [ADDL_EFFECT_GHOST_CURSE]       = SUBSCR_CURSE_GHOST,
    [ADDL_EFFECT_PREPARE_MESSAGE]   = SUBSCR_PRINT_MESSAGE,
    [ADDL_EFFECT_FORESIGHT]         = SUBSCR_FORESIGHT,
    [ADDL_EFFECT_PERISH_SONG]       = SUBSCR_START_PERISH_SONG,
    [ADDL_EFFECT_SET_WEATHER]       = SUBSCR_WEATHER_MESSAGE,
    [ADDL_EFFECT_SWAGGER]           = SUBSCR_SWAGGER,
    [ADDL_EFFECT_ATTRACT]           = SUBSCR_APPLY_ATTRACT,
    [ADDL_EFFECT_SAFEGUARD]         = SUBSCR_APPLY_SAFEGUARD,
    [ADDL_EFFECT_PRESENT_HEAL]      = SUBSCR_PRESENT_HEAL,
    [ADDL_EFFECT_MAGNITUDE]         = SUBSCR_MAGNITUDE,
    [ADDL_EFFECT_BATON_PASS]        = SUBSCR_BATON_PASS,
    [ADDL_EFFECT_BELLY_DRUM]        = SUBSCR_BELLY_DRUM,
    [ADDL_EFFECT_TELEPORT]          = SUBSCR_TELEPORT,
    [ADDL_EFFECT_BEAT_UP]           = SUBSCR_BEAT_UP_ATTACK_MESSAGE,
    [ADDL_EFFECT_STOCKPILE]         = SUBSCR_STOCKPILE,
    [ADDL_EFFECT_SWALLOW]           = SUBSCR_SWALLOW,
    [ADDL_EFFECT_TORMENT]           = SUBSCR_APPLY_TORMENT,
    [ADDL_EFFECT_FLATTER]           = SUBSCR_FLATTER,
    [ADDL_EFFECT_MEMENTO]           = SUBSCR_MEMENTO,
    [ADDL_EFFECT_CHARGE]            = SUBSCR_CHARGE,
    [ADDL_EFFECT_TAUNT]             = SUBSCR_APPLY_TAUNT,
    [ADDL_EFFECT_TRICK]             = SUBSCR_TRICK,
    [ADDL_EFFECT_ROLE_PLAY]         = SUBSCR_ROLE_PLAY,
    [ADDL_EFFECT_BREAK_SCREENS]     = SUBSCR_BREAK_SCREENS,
    [ADDL_EFFECT_YAWN]              = SUBSCR_YAWN,
    [ADDL_EFFECT_SKILL_SWAP]        = SUBSCR_SKILL_SWAP,
    [ADDL_EFFECT_REFRESH]           = SUBSCR_REFRESH,
    [ADDL_EFFECT_ROOST]             = SUBSCR_ROOST,
    [ADDL_EFFECT_CURE_SLEEP]        = SUBSCR_FORCE_WAKE_UP,
    [ADDL_EFFECT_GRAVITY]           = SUBSCR_APPLY_GRAVITY,
    [ADDL_EFFECT_MIRACLE_EYE]       = SUBSCR_MIRACLE_EYE,
    [ADDL_EFFECT_HEALING_WISH]      = SUBSCR_HEALING_WISH,
    [ADDL_EFFECT_TAILWIND]          = SUBSCR_APPLY_TAILWIND,
    [ADDL_EFFECT_CLOSE_COMBAT]      = SUBSCR_CLOSE_COMBAT_DEBUFF,
    [ADDL_EFFECT_POWER_TRICK]       = SUBSCR_POWER_TRICK,
    [ADDL_EFFECT_SUPPRESS_ABILITY]  = SUBSCR_GASTRO_ACID,
    [ADDL_EFFECT_LUCKY_CHANT]       = SUBSCR_APPLY_LUCKY_CHANT,
    [ADDL_EFFECT_POWER_SWAP]        = SUBSCR_POWER_SWAP,
    [ADDL_EFFECT_GUARD_SWAP]        = SUBSCR_GUARD_SWAP,
    [ADDL_EFFECT_WORRY_SEED]        = SUBSCR_WORRY_SEED,
    [ADDL_EFFECT_HEART_SWAP]        = SUBSCR_HEART_SWAP,
    [ADDL_EFFECT_FLARE_BLITZ]       = SUBSCR_FLARE_BLITZ,
    [ADDL_EFFECT_DEFOG]             = SUBSCR_DEFOG,
    [ADDL_EFFECT_HEAL_BLOCK]        = SUBSCR_APPLY_HEAL_BLOCK,
    [ADDL_EFFECT_U_TURN]            = SUBSCR_PIVOT_ATTACK,
    [ADDL_EFFECT_EMBARGO]           = SUBSCR_EMBARGO,
    [ADDL_EFFECT_EAT_BERRY]         = SUBSCR_PLUCK,
    [ADDL_EFFECT_FLING]             = SUBSCR_FLING,
    [ADDL_EFFECT_VOLT_TACKLE]       = SUBSCR_VOLT_TACKLE,
    [ADDL_EFFECT_TAKE_RECOIL_1_2]   = SUBSCR_RECOIL_1_2,
    [ADDL_EFFECT_BURN_AND_FLINCH]   = SUBSCR_BURN_OR_FLINCH,
    [ADDL_EFFECT_FREEZE_AND_FLINCH] = SUBSCR_FREEZE_OR_FLINCH,
    [ADDL_EFFECT_PARA_AND_FLINCH]   = SUBSCR_PARA_OR_FLINCH,
    [ADDL_EFFECT_CHATTER]           = SUBSCR_CHATTER,
    [ADDL_EFFECT_LUNAR_DANCE]       = SUBSCR_LUNAR_DANCE,
    [ADDL_EFFECT_PSYCHO_SHIFT]      = SUBSCR_PSYCHO_SHIFT,
    // Expanded effects mapping
    [ADDL_EFFECT_GROWTH]            = SUBSCR_GROWTH,
};
#endif

inline BOOL Moves_CheckTableMatch(u16 moveID, u16 moveTable[], u8 sizeOfTable, BOOL retOnMatch)
{
    for (u8 i = 0; i < sizeOfTable; i++) {
        if (moveTable[i] == moveID) {
            return retOnMatch;
        }
    }

    return retOnMatch;
}

static u16 sBoostedByMinimize[] = {
    MOVE_BODY_SLAM,
    MOVE_DRAGON_RUSH,
    MOVE_FLYING_PRESS,
    MOVE_HEAT_CRASH,
    MOVE_HEAVY_SLAM,
    MOVE_STEAMROLLER,
    MOVE_STOMP,
};

BOOL Moves_BoostedByMinimize(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sBoostedByMinimize, NELEMS(sBoostedByMinimize), TRUE);
}

static u16 sAuraOrPulseMoves[] = {
    MOVE_AURA_SPHERE,
    MOVE_DARK_PULSE,
    MOVE_DRAGON_PULSE,
    MOVE_HEAL_PULSE,
    MOVE_ORIGIN_PULSE,
    MOVE_TERRAIN_PULSE,
    MOVE_WATER_PULSE
};

BOOL Moves_IsAuraOrPulse(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sAuraOrPulseMoves, NELEMS(sAuraOrPulseMoves), TRUE);
}

static u16 sBitingMoves[] = {
    MOVE_BITE,
    MOVE_CRUNCH,
    MOVE_FIRE_FANG,
    MOVE_FISHIOUS_REND,
    MOVE_HYPER_FANG,
    MOVE_ICE_FANG,
    MOVE_JAW_LOCK,
    MOVE_POISON_FANG,
    MOVE_PSYCHIC_FANGS,
    MOVE_THUNDER_FANG,
};

BOOL Moves_IsBiting(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sBitingMoves, NELEMS(sBitingMoves), TRUE);
}

static u16 sRecklessBoosted[] = {
    MOVE_BRAVE_BIRD,
    MOVE_CHLOROBLAST,
    MOVE_DOUBLE_EDGE,
    MOVE_FLARE_BLITZ,
    MOVE_HEAD_CHARGE,
    MOVE_HEAD_SMASH,
    MOVE_HIGH_JUMP_KICK,
    MOVE_JUMP_KICK,
    MOVE_LIGHT_OF_RUIN,
    MOVE_SUBMISSION,
    MOVE_TAKE_DOWN,
    MOVE_VOLT_TACKLE,
    MOVE_WAVE_CRASH,
    MOVE_WILD_CHARGE,
    MOVE_WOOD_HAMMER
};

BOOL Moves_BoostedByReckless(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sRecklessBoosted, NELEMS(sRecklessBoosted), TRUE);
}

static u16 sPowderMoves[] = {
    MOVE_COTTON_SPORE,
    MOVE_MAGIC_POWDER,
    MOVE_POISON_POWDER,
    MOVE_POWDER,
    MOVE_RAGE_POWDER,
    MOVE_SLEEP_POWDER,
    MOVE_SPORE,
    MOVE_STUN_SPORE,
};

BOOL Moves_IsPowder(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sPowderMoves, NELEMS(sPowderMoves), TRUE);
}

static u16 sPunchingMoves[] = {
    MOVE_BULLET_PUNCH,
    MOVE_COMET_PUNCH,
    MOVE_DIZZY_PUNCH,
    MOVE_DOUBLE_IRON_BASH,
    MOVE_DRAIN_PUNCH,
    MOVE_DYNAMIC_PUNCH,
    MOVE_FIRE_PUNCH,
    MOVE_FOCUS_PUNCH,
    MOVE_HAMMER_ARM,
    MOVE_HEADLONG_RUSH,
    MOVE_ICE_HAMMER,
    MOVE_ICE_PUNCH,
    // MOVE_JET_PUNCH,
    MOVE_MACH_PUNCH,
    MOVE_MEGA_PUNCH,
    MOVE_METEOR_MASH,
    MOVE_PLASMA_FISTS,
    MOVE_POWER_UP_PUNCH,
    // MOVE_RAGE_FIST
    MOVE_SHADOW_PUNCH,
    MOVE_SKY_UPPERCUT,
    MOVE_SURGING_STRIKES,
    MOVE_THUNDER_PUNCH,
    MOVE_WICKED_BLOW,
};

BOOL Moves_IsPunching(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sPunchingMoves, NELEMS(sPunchingMoves), TRUE);
}

static u16 sSlashingMoves[] = {
    MOVE_AERIAL_ACE,
    MOVE_AIR_CUTTER,
    MOVE_AIR_SLASH,
    // MOVE_AQUA_CUTTER,
    MOVE_BEHEMOTH_BLADE,
    // MOVE_BITTER_BLADE
    MOVE_CEASELESS_EDGE,
    MOVE_CROSS_POISON,
    MOVE_CUT,
    MOVE_FURY_CUTTER,
    // MOVE_KOWTOW_CLEAVE,
    MOVE_LEAF_BLADE,
    MOVE_NIGHT_SLASH,
    // MOVE_POPULATION_BOMB,
    // MOVE_PSYBLADE,
    MOVE_PSYCHO_CUT,
    MOVE_RAZOR_LEAF,
    MOVE_RAZOR_SHELL,
    MOVE_SACRED_SWORD,
    MOVE_SLASH,
    MOVE_SOLAR_BLADE,
    MOVE_STONE_AXE,
    MOVE_X_SCISSOR,
};

BOOL Moves_IsSlashing(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sSlashingMoves, NELEMS(sSlashingMoves), TRUE);
}

static u16 sSoundMoves[] = {
    MOVE_BOOMBURST,
    MOVE_BUG_BUZZ,
    MOVE_CHATTER,
    MOVE_CLANGING_SCALES,
    MOVE_CLANGOROUS_SOUL,
    MOVE_CLANGOROUS_SOULBLAZE,      // Z-move
    MOVE_CONFIDE,
    MOVE_DISARMING_VOICE,
    MOVE_ECHOED_VOICE,
    MOVE_EERIE_SPELL,
    MOVE_GRASS_WHISTLE,
    MOVE_GROWL,
    MOVE_HEAL_BELL,
    MOVE_HOWL,
    MOVE_HYPER_VOICE,
    MOVE_METAL_SOUND,
    MOVE_NOBLE_ROAR,
    MOVE_OVERDRIVE,
    MOVE_PARTING_SHOT,
    MOVE_PERISH_SONG,
    MOVE_RELIC_SONG,
    MOVE_ROAR,
    MOVE_ROUND,
    MOVE_SCREECH,
    MOVE_SING,
    MOVE_SNARL,
    MOVE_SNORE,
    MOVE_SPARKLING_ARIA,
    MOVE_SUPERSONIC,
    // MOVE_TORCH_SONG,
    MOVE_UPROAR,
};

BOOL Moves_IsSound(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sSoundMoves, NELEMS(sSoundMoves), TRUE);
}

static u16 sCannotNormalizeMoves[] = {
    MOVE_HIDDEN_POWER,
    MOVE_JUDGMENT,
    MOVE_MULTI_ATTACK,
    MOVE_NATURAL_GIFT,
    MOVE_TECHNO_BLAST,
    MOVE_TERRAIN_PULSE,
    MOVE_WEATHER_BALL
};

BOOL Moves_CanNormalize(u16 moveID)
{
    return Moves_CheckTableMatch(moveID, sCannotNormalizeMoves, NELEMS(sCannotNormalizeMoves), FALSE);
}
