/* global.h */
GF_RAND = 0x0201D2E8 | 1;
Free = 0x020181C4 | 1;
Malloc = 0x02018144 | 1;

/* archive.h */
LoadFromNARC = 0x02006AA4 | 1;
LoadFromNARC_Malloc = 0x02006AC0 | 1;
LoadFromNARC_Offset = 0x02006AFC | 1;
LoadFromNARC_OffsetAndMalloc = 0x02006B18 | 1;

/* pokemon.h */
BoxPokemon_Get = 0x02074570 | 1;
BoxPokemon_Set = 0x02074C60 | 1;
BoxPokemon_Lock = 0x02073D20 | 1;
BoxPokemon_Unlock = 0x02073D48 | 1;
PokemonBaseStats_Get = 0x020759F0 | 1;
PokemonBaseStats_GetWithForm = 0x020759CC | 1;